# Generated by Django 3.0.5 on 2020-04-25 11:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chapbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapbook',
            name='mmsid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chapbook',
            name='preamble',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='preamble',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
