# Generated by Django 3.0.5 on 2020-04-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200425_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapbook',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
