# Generated by Django 3.0.5 on 2020-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chapbook_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='previewURL',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
